#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"
# Includes a custom 404 page containing "Ceci n'est pas une page".

#  updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install nginx

sudo -p mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
#  sets the content of the index file
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 and serve f
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.html;
}
" > /etc/nginx/sites-available/default

#  creates an empty file named 404.html inside the /etc/nginx/html directory.
sudo touch /etc/nginx/html/404.html

# Paste a 404 response in the 404.html file
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Display script completion message
echo "Nginx installation and configuration completed."

# Create a configuration file for the redirection
echo "server {
    listen      80;
    listen      [::]:80;
    root        /etc/nginx/html;
    index       index.html index.html;

    error_page 404 /404.html;
    location = /404 {
      root /etc/nginx/html;
      internal;
    }

}" | sudo tee /etc/nginx/sites-available/default
# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test nginx configuration and reload
sudo nginx -t
sudo service nginx reload
