#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"
# Includes a custom 404 page containing "Ceci n'est pas une page".

# Exit on error
set -e

# Update package lists for available software packages.
sudo apt-get update

# Install the Nginx web server.
sudo apt-get install -y nginx

# Create directories and files
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html

# Set content for index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

# Set content for 404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Configure Nginx
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /etc/nginx/html;
    index       index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
        internal;
    }
}
EOF

# Enable the new site configuration
sudo ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
